export const selectOptions = [
  {
    id: "1",
    placeholder: "0",
    regex: "matrix",
    value: "matrix",
  },
  {
    id: "2",
    placeholder: "0",
    regex: "matrix3d",
    value: "matrix3d",
  },
  {
    id: "3",
    placeholder: "0",
    regex: "lengthOne",
    value: "perspective",
  },
  {
    id: "4",
    placeholder: "0",
    regex: "lengthOne",
    value: "rotate",
  },
  {
    id: "5",
    placeholder: "0",
    regex: "rotate3d",
    value: "rotate3d",
  },
  {
    id: "6",
    placeholder: "0",
    regex: "angleOne",
    value: "rotateX",
  },
  {
    id: "7",
    placeholder: "0",
    regex: "angleOne",
    value: "rotateY",
  },
  {
    id: "8",
    placeholder: "0",
    regex: "angleOne",
    value: "rotateZ",
  },
  {
    id: "9",
    placeholder: "0",
    regex: "oneOrTwoNumbers",
    value: "scale",
  },
  {
    id: "10",
    placeholder: "0",
    regex: "threeNumbers",
    value: "scale3d",
  },
  {
    id: "11",
    placeholder: "0",
    regex: "angleOne",
    value: "scaleX",
  },
  {
    id: "12",
    placeholder: "0",
    regex: "angleOne",
    value: "scaleY",
  },
  {
    id: "13",
    placeholder: "0",
    regex: "angleOne",
    value: "scaleZ",
  },
  //  {
  //    id: "14",
  //    placeholder: "0",
  //    regex: "",
  //    value: "scale3d",
  //  },
  {
    id: "15",
    placeholder: "0",
    regex: "oneOrTwoAngles",
    value: "skew",
  },
  {
    id: "16",
    placeholder: "0",
    regex: "angleOne",
    value: "skewX",
  },
  {
    id: "17",
    placeholder: "0",
    regex: "angleOne",
    value: "skewY",
  },
  {
    id: "18",
    placeholder: "0",
    regex: "oneOrTwoLengthPercentages",
    value: "translate",
  },
  {
    id: "19",
    placeholder: "0",
    regex: "TwoLengthPercentagesAndLength",
    value: "translate3d",
  },
  {
    id: "20",
    placeholder: "0",
    regex: "oneLengthPercentage",
    value: "translateX",
  },
  {
    id: "21",
    placeholder: "0",
    regex: "oneLengthPercentage",
    value: "translateY",
  },
  {
    id: "22",
    placeholder: "0",
    regex: "oneLengthPercentage",
    value: "translateZ",
  },
];
