export const selectOptions = [
  {
    id: "1",
    placeholder: "1, 0.2, -1, 1, 3, 3",
    regex: "matrix",
    value: "matrix",
  },
  {
    id: "2",
    placeholder: "0.35,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0.2",
    regex: "matrix3d",
    value: "matrix3d",
  },
  {
    id: "3",
    placeholder: "500px",
    regex: "lengthOne",
    value: "perspective",
  },
  {
    id: "4",
    placeholder: "-45deg",
    regex: "angleOne",
    value: "rotate",
  },
  {
    id: "5",
    placeholder: "1, 1, 1, -45deg",
    regex: "rotate3d",
    value: "rotate3d",
  },
  {
    id: "6",
    placeholder: "-45deg",
    regex: "angleOne",
    value: "rotateX",
  },
  {
    id: "7",
    placeholder: "-45deg",
    regex: "angleOne",
    value: "rotateY",
  },
  {
    id: "8",
    placeholder: "-45deg",
    regex: "angleOne",
    value: "rotateZ",
  },
  {
    id: "9",
    placeholder: "0.75",
    regex: "oneOrTwoNumbers",
    value: "scale",
  },
  {
    id: "10",
    placeholder: "0.8, 0.8, 0.8",
    regex: "threeNumbers",
    value: "scale3d",
  },
  {
    id: "11",
    placeholder: "0.8",
    regex: "numberOne",
    value: "scaleX",
  },
  {
    id: "12",
    placeholder: "0.8",
    regex: "numberOne",
    value: "scaleY",
  },
  {
    id: "13",
    placeholder: "0.8",
    regex: "numberOne",
    value: "scaleZ",
  },
  {
    id: "15",
    placeholder: "30deg, 30deg",
    regex: "oneOrTwoAngles",
    value: "skew",
  },
  {
    id: "16",
    placeholder: "30deg",
    regex: "angleOne",
    value: "skewX",
  },
  {
    id: "17",
    placeholder: "30deg",
    regex: "angleOne",
    value: "skewY",
  },
  {
    id: "18",
    placeholder: "30%",
    regex: "oneOrTwoLengthPercentages",
    value: "translate",
  },
  {
    id: "19",
    placeholder: "45px, 45px, 45px",
    regex: "TwoLengthPercentagesAndLength",
    value: "translate3d",
  },
  {
    id: "20",
    placeholder: "100px",
    regex: "oneLengthPercentage",
    value: "translateX",
  },
  {
    id: "21",
    placeholder: "100px",
    regex: "oneLengthPercentage",
    value: "translateY",
  },
  {
    id: "22",
    placeholder: "100px",
    regex: "oneLengthPercentage",
    value: "translateZ",
  },
];
